:toc:
:sectnums:
:toc-title: 目次
:chapter-label:

= MySQLデータベースの規約

== テーブル作成規約
. 【必須】``YES/NO``を表すフィールドに``is_xxx``の形の名前を付ける。データタイプは``unsigned tinyint(1: YES 0: NO)``にする。
+
NOTE: フィールドが負数ではない場合は、必ず``unsigned``にする。

. 【必須】テーブル名とフィールド名に小文字/数字を使用する。数字から始まることと、２つのアンダースコアの間に数字のみであることを禁止する。フィールド名の変更にコストが大きいので、フィールド名について慎重に考える。
+
.説明:Windows環境では、MySQLは大文字と小文字を区別しないが、Linux環境では、デフォルトで区別する。よぅて、混乱をおこさないために、一律にデータベース名／テーブル名／フィールド名に大文字は使用禁止とする。
+
.良い例
[source,text]
----
department_name,rdc_config,level3_name
----
+
.悪い例
[source,text]
----
DepartmentName,rdcConfig,level_3_name
----
+
. 【必須】テーブル名に複数形の名前をつけない。
+
NOTE: テーブル名は、テーブルにあるデータ内容を表すが、データの数量を表すものではない。

. 【必須】予約語(``desc,range,match,delayed``など)の使用を禁止する。
+
. 【必須】主キーのインデックス名に``pk_``フィールド名、ユニークインデックス名に``ux_``フィールド名、一般のインデックス名に、``idx_``フィールド名の形でインデックス名をつける。
+
NOTE: ``pk_``は``primary key``の略称、``uk_``は``unique key``の略称、``idx_``は``index``の略称である
+
. 【必須】浮動小数点型は、``decimal``にする。``float``と``dobule``は使用禁止とする。
+
NOTE: ``float``と``dobule``に精度の問題があり、比較時に期待通りの結果にならない恐れがある。

. 【必須】文字列型のフィールドに保存される文字列の長さが同じであれば、固定長``char``型にする。
+
. 【必須】``varchar``は、可変長型文字列であり、長さは5000を超えないようにする。5000を超えたら、データタイプを``text``型にして、新しいテーブルを作成して保存する。主キーを用いて元のテーブルと関連をつける。
+
. 【必須】テーブルに必ず作成する三つのフィールドを:``id```、``create_time``、``update_time```
NOTE: ``id``は主キーであり、タイプは、``bigint unsigned auto increment``である。``create_time``と``update_time``は``datetime``型である。
+
. 【推奨】テーブル名には、"業務名_テーブルの機能"の形の名称をつける。
+
.良い例
[source,text]
----
trade_config / reserve_record / force_project
----
. 【推奨】データベース名は、アプリケーション名と一致させる。
+
. 【推奨】フィールドの使用目的を変更したとき、および表す区分値を追加した後に、フィールドのコメントも早めに更新する。
+
. 【推奨】パフォーマンス向上のために、テーブルの非正規化を考慮する。テーブルに追加した冗長のフィールドは、以下の条件を満たす必要がある。
+
* 変更される頻度が低い
* 長い``varchar``型ではない、もちろん``text``型は不可
* ユニークインデックスではないフィールド
+
. 【推奨】一つのテーブルのレコード数が500万を超えた場合、或いは、テーブルのサイズが2GBを超えた場合、テーブルの分割を検討する。
NOTE: 3年後にテーブルの容量が上記レベルにならないと推計した場合は、テーブルの分割をかんがえなくてよい。

. 【推奨】フィールドに適切な長さを持つデータ型を選択する。保存スペースの節約だけではなく、検索のスピードの向上にも役に立つ。


== インデックス規約

== SQL文

== ORMマッピング

